version: "3.7"
services:
  db:
    image: postgres:10
    container_name: postgres_10
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: bookstore
    ports:
      - 5432:5432
    # map init scripts
    volumes:
      - ./scripts/bookstore.sql:/docker-entrypoint-initdb.d/bookstore.sql

